# Test against this version of Node
environment:
    matrix: 
      # Node
      - nodejs_version: "6"

# Fix line endings
init:
  - git config --global core.autocrlf true

# Install scripts (run after repo cloning)
install:
  # Get the latest stable version of Node
  - ps: Write-Host "Installing node..."
  - ps: Install-Product node $env:nodejs_version

  # install modules
  - ps: Write-Host "Installing packages..."
  - npm install

# Post-install test scripts
test_script:
  # Output useful info for debugging
  - node --version
  - npm --version

  # Run tests
  - ps Write-Host "Running tests..."
  - npm test

  # Don't build
 build: off